services:
  - type: web
    name: connectplus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: connectplus-db
          property: connectionString
      - key: FLASK_DEBUG
        value: False

databases:
  - name: connectplus-db
    plan: free

